### ISSUE TITLE
Support json serialized filters

### ISSUE THREAD

**Issue by nandorstanko** [eosnewmedia/JSON-API-Server#1]
It would be great to support json stringified filter query param, it would give us more freedom.

Now there is an exception if the filter is not an array:
`if (!\is_array($query->getRequired('filter'))) {
                throw new \InvalidArgumentException('Invalid filter parameter given!');
            }`

My solution would be to decode the filter if it is a string.

Json api specification is not specific about the filter's type, so I think that this would be an enhancement, and there are some use cases for us right now...

**Comment by bogomolov-dev** [comment]
@nandorstanko, implemented in 2.5.1

**Comment by nandorstanko** [comment]
Great work, thanks!

**Comment by bogomolov-dev** [comment]
Sorry for the delay ;)
