### ISSUE TITLE
Relationships bug?

### ISSUE THREAD

**Issue by legendik** [eosnewmedia/JSON-API-Server#8]
Hi @pmarien,

I have created `JsonResource` with defined `relationships`. The problem is, that by default is `relationship` object removed from resource. It is shown only if you send request to resource with `?include`. I think this is a bug. The relationships must be shown by default everytime. Because otherwise you can't know what are the relationships.

I think this part of code should be removed [https://github.com/eosnewmedia/JSON-API-Server/blob/master/src/JsonApiServer.php#L215-L219](https://github.com/eosnewmedia/JSON-API-Server/blob/master/src/JsonApiServer.php#L215-L219) What do you think?

Or, do you have an idea how to show relationships by default? By default i mean send request to `http://server/{type}/{id}`.

**Comment by pmarien** [comment]
Hi @legendik, you are right, their is a bug, but not in this lib.
The bug is here: https://github.com/eosnewmedia/JSON-API-Common/blob/master/src/Model/Request/Request.php#L387
the condition must be or instead of and. I will fix it.

**Comment by pmarien** [comment]
https://github.com/eosnewmedia/JSON-API-Common/issues/13
